import {
  FileText,
  Scissors,
  Minimize2,
  Droplet,
  FileX,
  FileImage,
  FileType,
  Image,
  Maximize2,
  Combine,
  ImageIcon,
  FileSpreadsheet,
  Presentation,
} from 'lucide-react';

export interface Tool {
  id: string;
  label: string;
  description: string;
  route: string;
  icon: any;
  category: 'pdf' | 'image' | 'conversion';
}

export const TOOLS_CATALOG: Tool[] = [
  {
    id: 'merge-pdf',
    label: 'Merge PDF',
    description: 'Combine multiple PDF files into one document',
    route: '/merge-pdf',
    icon: Combine,
    category: 'pdf',
  },
  {
    id: 'split-pdf',
    label: 'Split PDF',
    description: 'Split a PDF into separate pages',
    route: '/split-pdf',
    icon: Scissors,
    category: 'pdf',
  },
  {
    id: 'compress-pdf',
    label: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining quality',
    route: '/compress-pdf',
    icon: Minimize2,
    category: 'pdf',
  },
  {
    id: 'resize-pdf',
    label: 'Resize PDF',
    description: 'Change PDF page size to A4, Letter, or other formats',
    route: '/resize-pdf',
    icon: Maximize2,
    category: 'pdf',
  },
  {
    id: 'remove-pages',
    label: 'Remove Pages',
    description: 'Delete specific pages from your PDF',
    route: '/remove-pages',
    icon: FileX,
    category: 'pdf',
  },
  {
    id: 'add-watermark',
    label: 'Add Watermark',
    description: 'Add text watermark to your PDF pages',
    route: '/add-watermark',
    icon: Droplet,
    category: 'pdf',
  },
  {
    id: 'pdf-to-word',
    label: 'PDF to Word',
    description: 'Convert PDF documents to editable Word files',
    route: '/pdf-to-word',
    icon: FileType,
    category: 'conversion',
  },
  {
    id: 'word-to-pdf',
    label: 'Word to PDF',
    description: 'Convert Word documents (.doc, .docx) to PDF format',
    route: '/word-to-pdf',
    icon: FileText,
    category: 'conversion',
  },
  {
    id: 'excel-to-pdf',
    label: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF format',
    route: '/tools/excel-to-pdf',
    icon: FileSpreadsheet,
    category: 'conversion',
  },
  {
    id: 'pdf-to-excel',
    label: 'PDF to Excel',
    description: 'Extract tables from PDF to Excel spreadsheet',
    route: '/tools/pdf-to-excel',
    icon: FileSpreadsheet,
    category: 'conversion',
  },
  {
    id: 'powerpoint-to-pdf',
    label: 'PowerPoint to PDF',
    description: 'Convert PowerPoint presentations to PDF',
    route: '/tools/powerpoint-to-pdf',
    icon: Presentation,
    category: 'conversion',
  },
  {
    id: 'pdf-to-powerpoint',
    label: 'PDF to PowerPoint',
    description: 'Convert PDF pages to PowerPoint slides',
    route: '/tools/pdf-to-powerpoint',
    icon: Presentation,
    category: 'conversion',
  },
  {
    id: 'pdf-to-jpg',
    label: 'PDF to JPG',
    description: 'Convert PDF documents to JPG images',
    route: '/tools/pdf-to-jpg',
    icon: FileImage,
    category: 'conversion',
  },
  {
    id: 'image-to-pdf',
    label: 'Image to PDF',
    description: 'Convert images (JPG, PNG) to PDF documents',
    route: '/image-to-pdf',
    icon: FileImage,
    category: 'conversion',
  },
  {
    id: 'jpg-to-jpeg',
    label: 'JPG to JPEG',
    description: 'Convert JPG images to JPEG format',
    route: '/tools/jpg-to-jpeg',
    icon: ImageIcon,
    category: 'conversion',
  },
  {
    id: 'jpeg-to-jpg',
    label: 'JPEG to JPG',
    description: 'Convert JPEG images to JPG format',
    route: '/tools/jpeg-to-jpg',
    icon: ImageIcon,
    category: 'conversion',
  },
  {
    id: 'resize-image',
    label: 'Resize Image',
    description: 'Resize and compress images to specific dimensions or file size',
    route: '/resize-image',
    icon: Image,
    category: 'image',
  },
];
